.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. gapcoin_qt test_gapcoin_qt
clean: FORCE
	$(MAKE) -C .. gapcoin_qt_clean test_gapcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_gapcoin_qt_check
gapcoin-qt gapcoin-qt.exe: FORCE
	 $(MAKE) -C .. gapcoin_qt
